// PDF generation for the IMEI verification report + certificate.
// Uses jsPDF (works inside the Capacitor WebView). On web it triggers a browser
// download; on native it writes to the cache dir and opens the share sheet so the
// user can save/share the file.
import { jsPDF } from 'jspdf'
import { Capacitor } from '@capacitor/core'
import { certificateHtml, CERT_WIDTH } from './certificateTemplate'

const PINK = [235, 38, 82]
const INK = [23, 23, 28]
const MUTED = [107, 114, 128]
const INDIGO = [46, 47, 129]

async function savePdf(doc, filename) {
  if (Capacitor.isNativePlatform()) {
    // Lazy-load native plugins so web builds don't pull them in.
    const [{ Filesystem, Directory }, { Share }] = await Promise.all([
      import('@capacitor/filesystem'),
      import('@capacitor/share'),
    ])
    const base64 = doc.output('datauristring').split(',')[1]
    const { uri } = await Filesystem.writeFile({
      path: filename,
      data: base64,
      directory: Directory.Cache,
    })
    await Share.share({ title: filename, url: uri })
  } else {
    doc.save(filename)
  }
}

const fmtDate = (iso) => {
  try {
    return new Date(iso || Date.now()).toLocaleString('en-IN', {
      dateStyle: 'long',
      timeStyle: 'medium',
    })
  } catch {
    return String(iso || '')
  }
}

const statusText = (s) =>
  ({ CLEAN: 'Clean — not blacklisted', BLOCKED: 'Blocked', STOLEN: 'Stolen', UNKNOWN: 'Not verified' }[s] ||
    s ||
    '—')

// Builds the IMEI verification report from the /ivs/verify response + form meta.
export async function downloadReport({ verify = {}, imei1, imei2, deviceModel, customerName } = {}) {
  const doc = new jsPDF({ unit: 'pt', format: 'a4' })
  const W = doc.internal.pageSize.getWidth()
  const M = 48
  let y = 56

  // header band
  doc.setFillColor(...PINK)
  doc.rect(0, 0, W, 8, 'F')
  doc.setFont('helvetica', 'bold').setFontSize(20).setTextColor(...INK)
  doc.text('GREST', M, y)
  doc.setFont('helvetica', 'normal').setFontSize(11).setTextColor(...MUTED)
  doc.text('Device Verification Services', M, y + 16)
  doc.setFont('helvetica', 'bold').setFontSize(13).setTextColor(...INDIGO)
  doc.text('IMEI Verification Report', W - M, y, { align: 'right' })
  doc.setFont('helvetica', 'normal').setFontSize(9).setTextColor(...MUTED)
  doc.text('Sanchar Saathi / CEIR', W - M, y + 15, { align: 'right' })

  y += 40
  doc.setDrawColor(236, 231, 236).line(M, y, W - M, y)
  y += 28

  const section = (title) => {
    doc.setFont('helvetica', 'bold').setFontSize(11).setTextColor(...PINK)
    doc.text(title.toUpperCase(), M, y)
    y += 18
  }
  const row = (label, value) => {
    doc.setFont('helvetica', 'normal').setFontSize(10).setTextColor(...MUTED)
    doc.text(String(label), M, y)
    doc.setFont('helvetica', 'bold').setFontSize(10).setTextColor(...INK)
    const lines = doc.splitTextToSize(String(value ?? '—'), W - M - 200)
    doc.text(lines, W - M, y, { align: 'right' })
    y += 14 * lines.length + 8
  }

  const reg1 = verify?.rawResponse?.imei1?.[imei1]

  section('Result')
  row('Status', statusText(verify.imei1Status))
  row('Transaction allowed', verify.allowTransaction ? 'Yes' : 'No')
  if (verify.message) row('Remark', verify.message)
  y += 6

  section('Device')
  row('IMEI 1', imei1 || '—')
  if (imei2) row('IMEI 2', imei2)
  if (deviceModel) row('Device / model', deviceModel)
  if (customerName) row('Customer', customerName)
  y += 6

  section('CEIR details')
  row('CDOT status (IMEI 1)', verify.imei1CdotStatus || '—')
  if (reg1) row('IMEI registered', reg1.imei_reg === 'yes' ? 'Yes' : 'No')
  if (imei2) row('CDOT status (IMEI 2)', verify.imei2CdotStatus || '—')
  y += 6

  section('Verification')
  row('Reference ID', verify.referenceId || '—')
  row('Verified at', fmtDate(verify.verifiedAt))
  row('Report generated', fmtDate(Date.now()))

  // footer
  const H = doc.internal.pageSize.getHeight()
  doc.setDrawColor(236, 231, 236).line(M, H - 60, W - M, H - 60)
  doc.setFont('helvetica', 'normal').setFontSize(8).setTextColor(...MUTED)
  doc.text(
    'This report reflects the CEIR / Sanchar Saathi blocklist status at the time of verification. Generated by the Grest app.',
    M,
    H - 44,
    { maxWidth: W - 2 * M }
  )

  await savePdf(doc, `Grest-IMEI-Report-${(imei1 || 'device').slice(-6)}.pdf`)
}

// Group a bare IMEI into the certificate's "35 123456 789012 3" layout.
const groupImei = (s) =>
  String(s || '')
    .replace(/\D/g, '')
    .replace(/(.{2})(.{6})(.{6})(.{1}).*/, '$1 $2 $3 $4')
    .trim() || '—'

const certDate = (iso) => {
  try {
    return new Date(iso || Date.now())
      .toLocaleString('en-IN', { day: '2-digit', month: 'short', year: 'numeric', hour: '2-digit', minute: '2-digit', hour12: false })
      .replace(',', ' ·')
  } catch {
    return String(iso || '')
  }
}

// Render an offscreen HTML node to a canvas with html2canvas. Waits for the
// certificate's images and web fonts so nothing rasterises blank.
async function htmlToCanvas(html) {
  const html2canvas = (await import('html2canvas')).default
  const host = document.createElement('div')
  host.style.cssText = `position:fixed; left:-100000px; top:0; width:${CERT_WIDTH}px; background:#fff; z-index:-1;`
  host.innerHTML = html
  document.body.appendChild(host)
  try {
    const imgs = Array.from(host.querySelectorAll('img'))
    await Promise.all(
      imgs.map((img) =>
        img.complete && img.naturalWidth
          ? Promise.resolve()
          : new Promise((res) => {
              img.onload = res
              img.onerror = res
            }),
      ),
    )
    if (document.fonts?.ready) await document.fonts.ready
    return await html2canvas(host.firstElementChild, {
      backgroundColor: '#ffffff',
      scale: 1,
      useCORS: true,
      logging: false,
      width: CERT_WIDTH,
      windowWidth: CERT_WIDTH,
    })
  } finally {
    document.body.removeChild(host)
  }
}

// Certificate of verification — rasterises the certificate.html design (populated
// from the verify result) and lays it onto one A4 page, centred, preserving aspect.
export async function downloadCertificate({ verify = {}, imei1, deviceModel } = {}) {
  const canvas = await htmlToCanvas(
    certificateHtml({
      imei: groupImei(imei1),
      device: deviceModel || '—',
      dateTime: certDate(verify.verifiedAt),
      statusLabel: verify.imei1Status === 'CLEAN' ? 'SAFE' : statusText(verify.imei1Status),
    }),
  )

  const doc = new jsPDF({ unit: 'pt', format: 'a4' })
  const W = doc.internal.pageSize.getWidth()
  const H = doc.internal.pageSize.getHeight()
  const M = 24
  const ratio = canvas.height / canvas.width
  let w = W - 2 * M
  let h = w * ratio
  if (h > H - 2 * M) {
    h = H - 2 * M
    w = h / ratio
  }
  const x = (W - w) / 2
  const y = (H - h) / 2
  doc.addImage(canvas.toDataURL('image/jpeg', 0.92), 'JPEG', x, y, w, h)

  await savePdf(doc, `Grest-Certificate-${(imei1 || 'device').slice(-6)}.pdf`)
}
